services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ural
      POSTGRES_PASSWORD: ural
      POSTGRES_DB: ural_team
    ports:
      - "5432:5432"
    volumes:
      - ural_pg:/var/lib/postgresql/data

volumes:
  ural_pg:
